### ISSUE TITLE
RxReprint retry doesn't retry correct number of times

### ISSUE THREAD

**Issue by brycehendrix** [ajalt/reprint#16]
I found that if I use `RxReprint.authenticate().retry(RxReprint.retryNonFatal(5))`, onError() will usually be called on the 6th failure (but not always). Changing that to  `RxReprint.authenticate().retry(RxReprint.retryNonFatal(2))` results in the same behavior, as does `RxReprint.authenticate().retry(RxReprint.retryNonFatal(1))`.

What I'm trying to go if give the user 3 tries, and tell the user on the 2nd try that if they do not succeed they will be logged out.

**Comment by ajalt** [comment]
So `retryNonFatal` was behaving as intended, but the docs were poorly written. I've updated them to make it clear that the parameter only applies to timeout failures, which is typically the only fatal reason you'd want to restart for.

I also added `RxReprint.retryLimitedAuthFailures` that will help out with what you're trying to do. Keep in mind that there are a lot of failure reasons that will prevent you from restarting the sensor. The system can lock the sensor whenever it wants if it thinks you've had too many incorrect authentication attempts, which is why you `onError` can get called sooner than you'd like.
