### ISSUE TITLE
CryptoObject

### ISSUE THREAD

**Issue by phileo** [ajalt/reprint#28]
I would like to pass a ```CryptoObject``` to the FingerprintManager and I am looking for the path of least resistance solution.

Is it better to build a brand new ReprintModule and call ```registerModule()``` with it?
Or should I try to modify the existing ```MarshmallowReprintModule```

Also, if I created a new ReprintModule with Crypto, will I need to modify the RxJava2 library?
Unrelated question, but I noticed that the Samsung SPass module is ignored on API 23+ devices.  Is this intended?

**Comment by ajalt** [comment]
I'll answer your second question first: By default, Reprint uses the spass module if it's available. It looks like newer samsung devices don't support it, and use the marshmallow module instead. 

w.r.t. the `CryptoObject`: I initially chose not to expose it in the Reprint since it's only applicable to the marshmallow module. I suppose the best solution would be to add an `authenticate` overload that takes a support library `CryptoObject` and passes it to the modules. But in the case that you're using a module that doesn't support it, what should the behavior be? It feels bad to throw an exception in the spass module when it gets a `CryptoObject`, but is authenticating the fingerprint without unlocking the `CryptoObject` useful?

**Comment by phileo** [comment]
I wound up creating a new ReprintModule that `extends MarshmallowReprintModule`.
I name it `CryptoAPI23ReprintModule`, and pass in the `CryptoObject` as one of the constructor parameters.

Then following the pattern of `MarshmallowReprintModule`, I implemented a private auth method which calls `fingerprintManager.authenticate()` with the `CryptoObject`

I also need to pass the CryptoObject back to the user, so the easiest way to do this was to create a new abstract class which `implements AuthenticationListener`.  Then I call this abstract class as follows in the `FingerprintManager.AuthenticationCallback.onAuthenticationSucceeded()` callback : 
 `listener.setCryptoObject(result.getCryptoObject())`

This works for my purposes.  However, I'm not sure whether this is too custom of a solution, or whether it is generic enough to be included into your Reprint library.  
Let me know what you think.

**Comment by ajalt** [comment]
I'm glad you found a solution that works! What do you do in the case when you're on a device that uses the SPass module, which doesn't support the `CryptoObject`?

**Comment by phileo** [comment]
hmmm..... I'm currently just calling `Reprint.registerModule()` and passing in my `CryptoAPI23ReprintModule` so  my I'm not sure what to do in that scenario, what would you suggest?

Should I create a `Reprint.initializeWithCrypto()` that checks whether I'm on a device that uses the SPass module, and if not, then call `registerModule(CryptoAPI23ReprintModule)` ?

**Comment by ajalt** [comment]
Ah, so you aren't using the spass module at all? Your design makes sense in that use case. Let me think more about a general solution. In the mean time, I'll leave this issue open, and if anyone else has a use case for the `CryptoObject`, they can comment on this issue to let me know what they'd like to see.

**Comment by kevbry** [comment]
@phileo Any chance you could post your CryptoAPI23ReprintModule? I'm looking for exactly the same thing.
