### ISSUE TITLE
onFailure is called for no reason

### ISSUE THREAD

**Issue by hatpick** [ajalt/reprint#4]
I'm using reprint on a phone with api 23 but no fingerprint sensor. onFailure gets called immediately.

**Comment by ajalt** [comment]
That's by design. What would you expect to happen?

**Comment by hatpick** [comment]
Nothing should happen, when you don't have a sensor but you have the api available on your phone you haven't tried your fingers for authentication, so no failure, no authentication should happen.

**Comment by ajalt** [comment]
No authentication does happen. I would be a terrible design to just never call any listener callbacks. If the user hasn't registered a fingerprint, `onFailure` is called with an error code of `NO_FINGERPRINTS_REGISTERED` so that your UI can inform the user. You can check `Reprint.hasFingerprintRegistered()` if you want to check for that situation before calling `Reprint.authenticate()`
